GET {{host}}/protected/data/settings
Content-Type: application/json
Accept-Language: ru_RU
X-PLUGIN-TOKEN: {{token}}

###

PUT {{host}}/protected/data/settings
Content-Type: application/json
Accept-Language: ru_RU
X-PLUGIN-TOKEN: {{token}}

{
  "main": {
    "login": "user",
    "password": "hello-world"
  },
  "sender_1": {
    "use": true,
    "name": "Logistic LTD",
    "INN": 12345678
  },
  "sender_2": {
    "use": null,
    "name": null,
    "INN": null
  }
}

###

PUT {{host}}/protected/data/settings
Content-Type: application/json
Accept-Language: ru_RU
X-PLUGIN-TOKEN: {{token}}

{
  "main": {
    "login": "user",
    "password": "hello-world"
  },
  "sender_1": {
    "use": false,
    "name": "Logistic LTD",
    "INN": 12345678
  },
  "sender_2": {
    "use": null,
    "name": null,
    "INN": null
  }
}

###